# Generated by Django 5.0.4 on 2024-04-20 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sell_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Sikkim', 'Sikkim'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Haryana', 'Haryana'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Meghalaya', 'Meghalaya'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Assam', 'Assam'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Himachal Pradesh', 'Himachal Pradesh'), ('West Bengal', 'West Bengal'), ('Nagaland', 'Nagaland'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Maharashtra', 'Maharashtra'), ('Uttarakhand', 'Uttarakhand'), ('Goa', 'Goa'), ('Kerala', 'Kerla'), ('Tamil Nadu', 'Tamil Nadu'), ('Gujarat', 'Gujrat'), ('Karnataka', 'Karnataka'), ('Mizoram', 'Mizoram'), ('Jharkhand', 'Jharkhand'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Punjab', 'Punjab'), ('Manipur', 'Manipur'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Rajasthan', 'Rajasthan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('W', 'Fine Wine and Spirits'), ('FA', 'Fashion and Accesories'), ('E', 'Electronics'), ('C', 'Collectibles'), ('JW', 'Jewelry and Watches'), ('AW', 'ArtWork'), ('VRB', 'Vintage and Rare Books'), ('RE', 'RealEstate'), ('VC', 'Vehicles')], max_length=3),
        ),
        migrations.AlterField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('result', 'Waiting for Decalre Result')], default='active', max_length=10),
        ),
    ]
