# Generated by Django 5.0.4 on 2024-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_products_sold_to_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Mizoram', 'Mizoram'), ('Gujarat', 'Gujrat'), ('Odisha', 'Odisha'), ('Kerala', 'Kerla'), ('Meghalaya', 'Meghalaya'), ('Rajasthan', 'Rajasthan'), ('Jharkhand', 'Jharkhand'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Tamil Nadu', 'Tamil Nadu'), ('Maharashtra', 'Maharashtra'), ('Telangana', 'Telangana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Puducherry', 'Puducherry'), ('Manipur', 'Manipur'), ('Chandigarh', 'Chandigarh'), ('Ladakh', 'Ladakh'), ('Goa', 'Goa'), ('Punjab', 'Punjab'), ('Bihar', 'Bihar'), ('Uttarakhand', 'Uttarakhand'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Nagaland', 'Nagaland'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Sikkim', 'Sikkim'), ('Chhattisgarh', 'Chhattisgarh'), ('Karnataka', 'Karnataka'), ('Lakshadweep', 'Lakshadweep'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Tripura', 'Tripura'), ('West Bengal', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('AW', 'ArtWork'), ('VC', 'Vehicles'), ('JW', 'Jewelry and Watches'), ('RE', 'RealEstate'), ('VRB', 'Vintage and Rare Books'), ('E', 'Electronics'), ('C', 'Collectibles'), ('W', 'Fine Wine and Spirits'), ('FA', 'Fashion and Accesories')], max_length=3),
        ),
    ]
