# Generated by Django 5.0.4 on 2024-04-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0003_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu'), ('Goa', 'Goa'), ('Punjab', 'Punjab'), ('Tripura', 'Tripura'), ('Chandigarh', 'Chandigarh'), ('Ladakh', 'Ladakh'), ('Uttarakhand', 'Uttarakhand'), ('Mizoram', 'Mizoram'), ('Bihar', 'Bihar'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Manipur', 'Manipur'), ('Haryana', 'Haryana'), ('Chhattisgarh', 'Chhattisgarh'), ('Odisha', 'Odisha'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Rajasthan', 'Rajasthan'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Jharkhand', 'Jharkhand'), ('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Maharashtra', 'Maharashtra'), ('Nagaland', 'Nagaland'), ('Sikkim', 'Sikkim'), ('Gujarat', 'Gujrat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Lakshadweep', 'Lakshadweep'), ('Karnataka', 'Karnataka'), ('Meghalaya', 'Meghalaya'), ('Kerala', 'Kerla'), ('Telangana', 'Telangana'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Puducherry', 'Puducherry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('AW', 'ArtWork'), ('W', 'Fine Wine and Spirits'), ('VC', 'Vehicles'), ('VRB', 'Vintage and Rare Books'), ('RE', 'RealEstate'), ('C', 'Collectibles'), ('FA', 'Fashion and Accesories'), ('JW', 'Jewelry and Watches')], max_length=3),
        ),
    ]
