# Generated by Django 5.0.4 on 2024-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0003_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Nagaland', 'Nagaland'), ('Bihar', 'Bihar'), ('Meghalaya', 'Meghalaya'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Jharkhand', 'Jharkhand'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Rajasthan', 'Rajasthan'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Telangana', 'Telangana'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Haryana', 'Haryana'), ('Karnataka', 'Karnataka'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Uttarakhand', 'Uttarakhand'), ('Tamil Nadu', 'Tamil Nadu'), ('Lakshadweep', 'Lakshadweep'), ('Maharashtra', 'Maharashtra'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujrat'), ('Kerala', 'Kerla'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Puducherry', 'Puducherry'), ('Mizoram', 'Mizoram'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Manipur', 'Manipur'), ('West Bengal', 'West Bengal'), ('Tripura', 'Tripura'), ('Ladakh', 'Ladakh'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Madhya Pradesh', 'Madhya Pradesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('On The Way', 'On The Way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('VRB', 'Vintage and Rare Books'), ('FA', 'Fashion and Accesories'), ('VC', 'Vehicles'), ('C', 'Collectibles'), ('W', 'Fine Wine and Spirits'), ('AW', 'ArtWork'), ('RE', 'RealEstate'), ('E', 'Electronics'), ('JW', 'Jewelry and Watches')], max_length=3),
        ),
    ]
